import { nowIso } from './types.js';
import {
  FAQ_REPLY_KNOWLEDGE_BASE,
  FAQ_RISK_RULES,
} from './faq-knowledge-base.js';

export const DEFAULT_STRATEGY_CONFIG = {
  lowRiskDefaultAction: 'draft_only',
  mediumRiskDefaultAction: 'human_review',
  highRiskDefaultAction: 'human_review',
  spamDefaultAction: 'ignore_spam',
};

export const DEFAULT_AGENT_PIPELINE = {
  enabled: true,
  traceEnabled: true,
  defaultFailurePolicy: 'fail_closed',
};

export const DEFAULT_AGENT_SKILLS = [
  {
    id: 'skill-translate-global-language',
    key: 'translate_global_language',
    label: '全球语言识别与翻译',
    description: '识别客户来信语种，生成中文内部理解，并约束后续客户回复沿用客户语种。',
    enabled: true,
    order: 10,
    required: true,
    failurePolicy: 'fail_closed',
    notes: '输入：邮件主题、正文和历史摘要。输出：customerLanguage、translationZh、translationSource。边界：翻译只用于内部理解，不改写客户事实；无法识别语种时默认英文并提示人工确认。',
  },
  {
    id: 'skill-classify-email',
    key: 'classify_email',
    label: '邮件分类与意图识别',
    description: '识别咨询、售中、售后、退款、投诉、垃圾邮件等意图，并给出风险等级和建议动作。',
    enabled: true,
    order: 20,
    required: true,
    failurePolicy: 'fail_closed',
    notes: '优先判垃圾邮件，再判业务意图。低风险限售前标准咨询；订单状态、物流事实、取消、退换货、质量、补发、折扣、法律、平台投诉和差评统一进入人工审核。',
  },
  {
    id: 'skill-retrieve-knowledge',
    key: 'retrieve_knowledge',
    label: '知识库检索与依据选择',
    description: '按意图、关键词和风险等级检索 FAQ、政策、标准话术和禁用表达，作为回复主要依据。',
    enabled: true,
    order: 30,
    required: false,
    failurePolicy: 'skip_optional',
    notes: '优先使用常见问题及回复话术知识库；命中多条时按 priority 选择最高优先级。不得把未命中的内容当作事实；无依据时转人工或只生成收集信息话术。',
  },
  {
    id: 'skill-draft-reply',
    key: 'draft_reply',
    label: '回复草稿生成',
    description: '基于客户语种、风险结果和知识库标准话术生成可审核草稿或内部处理建议。',
    enabled: true,
    order: 40,
    required: true,
    failurePolicy: 'fail_closed',
    notes: '低风险可生成客户可见草稿；中高风险优先生成内部建议。必须同语种回复，不编造订单、物流、仓库、附件、退款、补发、折扣、赔偿或法律结论。',
  },
  {
    id: 'skill-review-risk',
    key: 'review_risk',
    label: '二次风险审核',
    description: '在生成后复查退款、法律、赔偿、补发、价格承诺、隐私、占位符和编造信息风险。',
    enabled: true,
    order: 50,
    required: true,
    failurePolicy: 'fail_closed',
    notes: '发现高风险、禁用表达、占位符、未核实运单号、未上传附件却引用附件、承认责任或利益承诺时，必须阻断自动发送并转人工。',
  },
  {
    id: 'skill-human-feedback',
    key: 'human_feedback',
    label: '人工反馈学习',
    description: '记录人工改判、人工修改、发送/归档/恢复系统判定和转人工原因，沉淀后续优化样本。',
    enabled: true,
    order: 60,
    required: false,
    failurePolicy: 'skip_optional',
    notes: '保存人工原稿、AI 草稿、最终发送内容、风险改判、命中知识库和处理结果。后续用于优化关键词、知识库优先级和提示词边界。',
  },
];

export function createDefaultEmailAIStore() {
  const timestamp = nowIso();
  const withTimestamps = (item) => ({
    ...item,
    createdAt: timestamp,
    updatedAt: timestamp,
  });

  return {
    schemaVersion: 1,
    modelProviders: [
      {
        id: 'provider-local-mock',
        name: 'Local Mock',
        providerKey: 'local_mock',
        baseUrl: '',
        apiKeyEnvName: '',
        defaultModel: 'local-mock-email-ai',
        supportedModels: ['local-mock-email-ai'],
        enabled: true,
        usageType: 'both',
        isFallback: true,
        temperature: 0.2,
        maxTokens: 1200,
        timeoutMs: 5000,
        retryCount: 0,
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    riskRules: [
      {
        id: 'risk-low-general-question',
        name: '低风险普通咨询',
        riskLevel: 'low',
        keywords: ['product', 'material', 'size', 'color', 'stock', '产品', '材质', '尺寸', '颜色', '库存', '咨询'],
        semanticDescription: '普通售前或产品基础咨询，不涉及投诉、退款、赔偿、平台处罚或强烈情绪。',
        conditionType: 'keyword_or_semantic',
        priority: 10,
        suggestedAction: 'draft_only',
        enabled: true,
        version: 1,
        notes: '默认只生成草稿，由工作台决定是否允许后续动作。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-low-logistics-query',
        name: '低风险物流查询',
        riskLevel: 'low',
        keywords: ['shipping information', 'tracking number', '物流查询', '物流单号', '发货时间普通询问'],
        semanticDescription: '普通物流状态询问，不包含异常、催促、投诉或承诺诉求。',
        conditionType: 'keyword_or_semantic',
        priority: 9,
        suggestedAction: 'draft_only',
        enabled: true,
        version: 1,
        notes: '仅确认收到并引导补充订单定位信息。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-medium-customer-unhappy',
        name: '中风险客户不满',
        riskLevel: 'medium',
        keywords: ['not satisfied', 'unhappy', 'disappointed', 'worried', 'asked many times', '不满意', '焦急', '多次追问', '催促'],
        semanticDescription: '客户表达不满、焦急或反复追问，但尚未明确投诉、退款、赔偿或法律威胁。',
        conditionType: 'keyword_or_semantic',
        priority: 30,
        suggestedAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '生成草稿但需要人工审核。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-medium-logistics-abnormal',
        name: '中风险物流异常',
        riskLevel: 'medium',
        keywords: ['logistics abnormal', 'delayed', 'delay', 'package not moving', 'not received any update', '物流异常', '发货延迟', '没有更新', '包裹异常'],
        semanticDescription: '物流异常、延迟或客户催促履约，不能自动承诺发货或到货时间。',
        conditionType: 'keyword_or_semantic',
        priority: 35,
        suggestedAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '需要人工核对物流状态。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-high-refund-dispute',
        name: '高风险退款争议',
        riskLevel: 'high',
        keywords: ['refund', 'return', 'chargeback', '退款', '退货', '拒付', '退钱'],
        semanticDescription: '客户明确要求退款、退货或发生支付争议。',
        conditionType: 'keyword_or_semantic',
        priority: 80,
        suggestedAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '禁止自动发送，进入人工处理。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-high-legal-threat',
        name: '高风险法律威胁',
        riskLevel: 'high',
        keywords: ['lawyer', 'legal', 'court', 'fraud', 'scam', '律师', '法院', '法律', '欺诈', '诈骗'],
        semanticDescription: '涉及律师、法院、法律责任、欺诈或虚假宣传。',
        conditionType: 'keyword_or_semantic',
        priority: 95,
        suggestedAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '只允许内部建议。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-high-platform-complaint',
        name: '高风险平台投诉',
        riskLevel: 'high',
        keywords: ['complain to platform', 'platform complaint', 'platform penalty', '投诉平台', '平台投诉', '平台处罚'],
        semanticDescription: '客户或平台官方提到投诉、处罚或平台介入。',
        conditionType: 'keyword_or_semantic',
        priority: 90,
        suggestedAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '涉及平台声誉和处罚风险。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'risk-high-bad-review-threat',
        name: '高风险差评威胁',
        riskLevel: 'high',
        keywords: ['bad review', 'negative review', 'one star', '差评', '负面评价', '一星'],
        semanticDescription: '客户威胁差评或负面公开评价。',
        conditionType: 'keyword_or_semantic',
        priority: 85,
        suggestedAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '品牌声誉风险，不能自动承诺。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      ...FAQ_RISK_RULES.map(withTimestamps),
    ],
    spamRules: [
      {
        id: 'spam-ad-promotion',
        name: '广告推广',
        ruleType: 'promotion',
        keywords: ['promotion', 'advertising', 'seo', 'backlinks', '推广', '广告', '外链'],
        senderEmails: [],
        senderDomains: [],
        urlPatterns: [],
        priority: 50,
        suggestedAction: 'ignore_spam',
        enabled: true,
        version: 1,
        notes: '明显广告和外链推广。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'spam-suspicious-link',
        name: '可疑链接',
        ruleType: 'suspicious_link',
        keywords: ['click here', 'login now', 'verify account', '点击链接', '立即登录', '验证账户'],
        senderEmails: [],
        senderDomains: [],
        urlPatterns: ['bit.ly', 'tinyurl', 'login-verify', 'account-secure'],
        priority: 70,
        suggestedAction: 'block_auto_reply',
        enabled: true,
        version: 1,
        notes: '诱导点击或可疑短链。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'spam-unrelated-marketing',
        name: '无关营销',
        ruleType: 'irrelevant_marketing',
        keywords: ['casino', 'loan', 'invoice service', 'mass marketing', '赌博', '贷款', '发票', '刷单', '代运营'],
        senderEmails: [],
        senderDomains: [],
        urlPatterns: [],
        priority: 60,
        suggestedAction: 'ignore_spam',
        enabled: true,
        version: 1,
        notes: '与业务无关的灰产或营销内容。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'spam-garbled-mail',
        name: '乱码邮件',
        ruleType: 'garbled',
        keywords: ['乱码', '无效内容', 'asdfasdf', 'qwertyuiop', 'test spam'],
        senderEmails: [],
        senderDomains: [],
        urlPatterns: [],
        priority: 40,
        suggestedAction: 'ignore_spam',
        enabled: true,
        version: 1,
        notes: '正文大量乱码或模板重复。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'spam-phishing',
        name: '钓鱼邮件',
        ruleType: 'phishing',
        keywords: ['password expired', 'account suspended', 'verify your mailbox', '密码过期', '账户暂停', '钓鱼'],
        senderEmails: [],
        senderDomains: [],
        urlPatterns: ['password', 'mailbox-login', 'verify'],
        priority: 90,
        suggestedAction: 'block_auto_reply',
        enabled: true,
        version: 1,
        notes: '可疑登录或凭证诱导。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    knowledgeBase: [
      {
        id: 'kb-product-general',
        title: '普通产品咨询回复',
        category: '产品信息咨询',
        applicableRiskLevels: ['low'],
        keywords: ['product', 'material', 'size', 'color', 'stock', '产品', '材质', '尺寸', '颜色', '库存'],
        customerScenario: '客户询问产品基础信息。',
        standardReply: 'Hello, thank you for reaching out. We have received your product question. Please share the specific style, size, material or color you are interested in, and our support team will help confirm the details.',
        forbiddenExpressions: ['guarantee', 'always available', '一定有货'],
        recommendedTone: 'polite',
        allowForAutoReply: false,
        requireHumanReview: false,
        priority: 30,
        enabled: true,
        version: 1,
        notes: '低风险产品咨询草稿。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'kb-logistics-query',
        title: '物流查询回复',
        category: '物流咨询',
        applicableRiskLevels: ['low', 'medium'],
        keywords: ['shipping', 'tracking', 'package', 'logistics', '物流', '快递', '包裹'],
        customerScenario: '客户询问物流或包裹状态。',
        standardReply: 'Hello, we have received your shipping inquiry. To avoid inaccurate information, please share your order number or order email if available, and our support team will check the latest shipping status.',
        forbiddenExpressions: ['arrive tomorrow', 'already shipped', '一定到货', '马上发货'],
        recommendedTone: 'polite',
        allowForAutoReply: false,
        requireHumanReview: true,
        priority: 25,
        enabled: true,
        version: 1,
        notes: '物流状态需人工核对。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'kb-shipping-delay',
        title: '发货延迟安抚回复',
        category: '发货延迟',
        applicableRiskLevels: ['medium'],
        keywords: ['delay', 'delayed', 'not received any update', '发货延迟', '没有更新'],
        customerScenario: '客户催促发货或物流长时间无更新。',
        standardReply: 'Hello, we understand your concern. We have received your message and will ask support to verify the order and shipping status before replying with confirmed information.',
        forbiddenExpressions: ['ship today', 'arrive tomorrow', 'guaranteed delivery', '今天发货', '明天到'],
        recommendedTone: 'calm',
        allowForAutoReply: false,
        requireHumanReview: true,
        priority: 40,
        enabled: true,
        version: 1,
        notes: '安抚但不承诺时效。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'kb-refund-cautious',
        title: '退款咨询谨慎回复',
        category: '退款咨询',
        applicableRiskLevels: ['high'],
        keywords: ['refund', 'return', '退款', '退货'],
        customerScenario: '客户询问退款或退货。',
        standardReply: '',
        forbiddenExpressions: ['we will refund', 'refund approved', '可以退款', '马上退款'],
        recommendedTone: 'calm',
        allowForAutoReply: false,
        requireHumanReview: true,
        priority: 90,
        enabled: true,
        version: 1,
        notes: '高风险只生成内部建议。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'kb-complaint-internal',
        title: '投诉类内部建议',
        category: '投诉安抚',
        applicableRiskLevels: ['high'],
        keywords: ['complaint', 'complain', 'bad review', '投诉', '差评'],
        customerScenario: '投诉、差评或平台投诉风险。',
        standardReply: '',
        forbiddenExpressions: ['we admit fault', 'compensation', '承认责任', '赔偿'],
        recommendedTone: 'calm',
        allowForAutoReply: false,
        requireHumanReview: true,
        priority: 95,
        enabled: true,
        version: 1,
        notes: '提醒人工核对平台规则和订单事实。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'kb-high-risk-no-auto-reply',
        title: '高风险邮件禁止自动回复说明',
        category: '高风险内部建议',
        applicableRiskLevels: ['high'],
        keywords: ['legal', 'lawyer', 'platform', 'chargeback', '法律', '律师', '平台', '拒付'],
        customerScenario: '法律、平台、拒付或品牌风险。',
        standardReply: '',
        forbiddenExpressions: ['legal responsibility', 'we are responsible', '法律责任', '我们负责'],
        recommendedTone: 'internal',
        allowForAutoReply: false,
        requireHumanReview: true,
        priority: 100,
        enabled: true,
        version: 1,
        notes: '仅用于内部建议，不生成客户可见回复。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      ...FAQ_REPLY_KNOWLEDGE_BASE.map(withTimestamps),
    ],
    promptTemplates: [
      {
        id: 'prompt-risk-check',
        name: '风险判定提示词',
        promptType: 'risk_check',
        systemPrompt: [
          'You are the risk and intent classifier for a customer service email agent.',
          'Classify the email by business intent first, then assign spam, low, medium or high risk.',
          'Low risk is limited to generic pre-sales FAQ questions that do not require order, warehouse, logistics, refund, return, exchange, compensation, legal or platform verification.',
          'Any order-specific status, shipping fact, cancellation, refund, return, exchange, quality complaint, missing package, attachment-dependent answer, discount, compensation, legal threat, platform complaint or bad-review threat requires human review.',
        ].join('\n'),
        taskPrompt: [
          'Return a strict JSON object with spam, risk, matched rules, suggested action and human-review reason.',
          'Use high risk when the agent would need to verify order data, logistics data, warehouse status, evidence, attachments, after-sales policy or financial decisions before replying.',
          'Use medium risk for unclear intent, mild dissatisfaction or incomplete information that still needs a human check.',
          'Use low risk only for standard pre-sales FAQ answers from the approved knowledge base.',
        ].join('\n'),
        outputFormat: {
          spam: { isSpam: false, confidence: 0, reasons: [] },
          risk: { level: 'low', reasons: [], matchedRules: [] },
          finalAction: 'draft_only',
        },
        enabled: true,
        version: 1,
        notes: '按“售前低风险、售中售后人工审核”的现有逻辑重写。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'prompt-reply-generation',
        name: '回复生成提示词',
        promptType: 'reply_generation',
        systemPrompt: [
          'You are the reply drafting skill inside an email agent.',
          'The approved knowledge base is the primary reference standard. Preserve its facts, constraints, forbidden expressions and human-review flags.',
          'Customer-facing replies must use the same language as the customer email. If the knowledge base standard reply is Chinese, translate it faithfully into the customer language without adding new facts.',
          'Never fabricate order status, tracking numbers, warehouse checks, delivery dates, attachments, refund approvals, replacement approvals, discounts, compensation, legal conclusions or platform outcomes.',
        ].join('\n'),
        taskPrompt: [
          'Return strict JSON with reply.draft, reply.translationZh, reply.internalSuggestion and reply.tone.',
          'For low-risk FAQ matches, draft a concise customer-facing reply based on the matched standardReply.',
          'For medium or high risk, or when a matched knowledge entry has requireHumanReview=true, keep customer-facing commitments conservative. If facts must be verified or placeholders are present, leave draft empty and put the suggested handling plus matched standardReply in internalSuggestion.',
          'Do not include placeholders such as 123, [tracking number], [人工填写], [附件] in a customer-facing draft.',
          'Do not send or imply refunds, returns, exchanges, discounts, compensation, free reshipment, exact shipment time or fault admission unless a human has confirmed it.',
        ].join('\n'),
        outputFormat: {
          reply: {
            draft: '',
            translationZh: '',
            internalSuggestion: '',
            tone: 'polite',
          },
        },
        enabled: true,
        version: 1,
        notes: '以知识库标准话术为主，支持全球语言同语种回复；中高风险默认内部建议。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'prompt-output-format',
        name: '输出格式提示词',
        promptType: 'output_safety_check',
        systemPrompt: 'Return a strict JSON object for the email workbench. Do not include markdown fences or prose outside JSON.',
        taskPrompt: [
          'The workbench parses spam, risk, reply, safety and finalAction from JSON.',
          'Set safety.needHumanReview=true when the draft includes or depends on unverified order facts, logistics facts, attachments, refunds, returns, exchanges, discounts, compensation, legal statements, platform claims or placeholders.',
          'Set safety.blocked=true when the draft contains forbidden promises, fabricated facts or customer-facing placeholders.',
        ].join('\n'),
        outputFormat: {
          spam: { isSpam: false, confidence: 0.2, reasons: [] },
          risk: { level: 'low', reasons: [], matchedRules: [] },
          reply: { draft: '', internalSuggestion: '', tone: 'polite' },
          safety: { needHumanReview: false, blocked: false, reasons: [] },
          finalAction: 'draft_only',
        },
        enabled: true,
        version: 1,
        notes: '统一输出格式。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    outputSafetyRules: [
      {
        id: 'safety-no-refund-promise',
        name: '禁止承诺退款',
        keywords: ['we will refund', 'refund approved', 'refund today', '可以退款', '马上退款', '同意退款', '承诺退款'],
        semanticDescription: '禁止在自动回复中承诺退款或退款时间。',
        riskLevel: 'high',
        triggerAction: 'block_auto_reply',
        enabled: true,
        version: 1,
        notes: '资金相关承诺必须人工审核。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'safety-no-compensation-promise',
        name: '禁止承诺赔偿',
        keywords: ['compensate', 'compensation', '赔偿', '补偿', '赔付'],
        semanticDescription: '禁止承诺赔偿、补偿或优惠。',
        riskLevel: 'high',
        triggerAction: 'block_auto_reply',
        enabled: true,
        version: 1,
        notes: '利益让渡必须人工确认。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'safety-no-reship-promise',
        name: '禁止承诺补发',
        keywords: ['reship', 'send a replacement', '补发', '重新发货'],
        semanticDescription: '禁止承诺补发或重新发货。',
        riskLevel: 'high',
        triggerAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '补发需核对订单和售后规则。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'safety-no-legal-liability',
        name: '禁止承认法律责任',
        keywords: ['we are legally responsible', 'admit liability', 'legal responsibility', '承认法律责任', '我们负责法律问题'],
        semanticDescription: '禁止承认法律责任或作出法律结论。',
        riskLevel: 'high',
        triggerAction: 'block_auto_reply',
        enabled: true,
        version: 1,
        notes: '法律风险必须人工处理。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'safety-no-fabricated-order',
        name: '禁止编造订单信息',
        keywords: ['your order is confirmed', 'order has been changed', '订单已修改', '订单正常', '已确认订单'],
        semanticDescription: '禁止在未核对系统时编造订单状态。',
        riskLevel: 'medium',
        triggerAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '订单信息必须从系统核对。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'safety-no-fabricated-logistics',
        name: '禁止编造物流信息',
        keywords: ['already shipped', 'tracking number', 'will arrive tomorrow', 'arrive tomorrow', '已经发货', '物流单号', '明天到货'],
        semanticDescription: '禁止编造物流状态、物流单号或到货时间。',
        riskLevel: 'medium',
        triggerAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '物流必须核对后再回复。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
      {
        id: 'safety-no-absolute-expression',
        name: '禁止绝对化表达',
        keywords: ['guarantee', 'always', 'never', '一定', '保证', '绝对'],
        semanticDescription: '避免绝对化和过度承诺表达。',
        riskLevel: 'medium',
        triggerAction: 'human_review',
        enabled: true,
        version: 1,
        notes: '客服表达应克制。',
        createdAt: timestamp,
        updatedAt: timestamp,
      },
    ],
    strategyConfig: { ...DEFAULT_STRATEGY_CONFIG },
    agentSkills: DEFAULT_AGENT_SKILLS.map((skill) => ({
      ...skill,
      createdAt: timestamp,
      updatedAt: timestamp,
    })),
    agentPipeline: { ...DEFAULT_AGENT_PIPELINE },
    configVersions: [],
    testRuns: [],
  };
}

export function createEmailAIConfigSnapshot(store = createDefaultEmailAIStore()) {
  return {
    modelConfig: store.modelProviders || [],
    riskRulesSnapshot: store.riskRules || [],
    spamRulesSnapshot: store.spamRules || [],
    knowledgeBaseSnapshot: store.knowledgeBase || [],
    promptTemplatesSnapshot: store.promptTemplates || [],
    outputSafetyRulesSnapshot: store.outputSafetyRules || [],
    agentSkillsSnapshot: store.agentSkills || [],
    agentPipelineSnapshot: {
      ...DEFAULT_AGENT_PIPELINE,
      ...(store.agentPipeline || {}),
    },
    strategyConfigSnapshot: {
      ...DEFAULT_STRATEGY_CONFIG,
      ...(store.strategyConfig || {}),
    },
  };
}
