export const sampleMails = [
  {
    id: 'FMAIL-001',
    subject: '已发送资料，请查收',
    sender: 'buyer001@example.test',
    receivedAt: '2026-06-10 09:12',
    summary: '客户只说明资料已发送，希望确认收到。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-002',
    subject: '我想查询订单',
    sender: 'buyer002@example.test',
    receivedAt: '2026-06-10 09:28',
    summary: '客户要查订单，但是没有提供订单号或下单邮箱。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-003',
    subject: '请问客服什么时候回复',
    sender: 'buyer003@example.test',
    receivedAt: '2026-06-10 10:03',
    summary: '客户询问客服处理时间，没有具体高风险诉求。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-004',
    subject: 'Order SH-TEST-1001 status',
    sender: 'buyer004@example.test',
    receivedAt: '2026-06-10 10:25',
    summary: '客户提供测试订单号，询问订单状态。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-005',
    subject: 'Where is my package',
    sender: 'buyer005@example.test',
    receivedAt: '2026-06-10 10:54',
    summary: '客户询问物流位置。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-006',
    subject: 'Product issue after receiving',
    sender: 'buyer006@example.test',
    receivedAt: '2026-06-10 11:15',
    summary: '客户说收到商品后有问题，未提出退款。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-007',
    subject: 'Collaboration request',
    sender: 'creator001@example.test',
    receivedAt: '2026-06-10 11:37',
    summary: '达人询问合作、报价和寄样。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-008',
    subject: 'I want a refund',
    sender: 'buyer008@example.test',
    receivedAt: '2026-06-10 13:08',
    summary: '客户明确要求退款。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-009',
    subject: 'I will leave a bad review',
    sender: 'buyer009@example.test',
    receivedAt: '2026-06-10 13:22',
    summary: '客户威胁差评并要求解决。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-010',
    subject: 'Please change my address today',
    sender: 'buyer010@example.test',
    receivedAt: '2026-06-10 14:06',
    summary: '客户要求修改收货地址并尽快发货。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-011',
    subject: '补充下单邮箱',
    sender: 'buyer011@example.test',
    receivedAt: '2026-06-10 14:16',
    summary: '客户说自己忘记使用哪个邮箱下单，未提供下单邮箱。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-012',
    subject: '非工作时间咨询',
    sender: 'buyer012@example.test',
    receivedAt: '2026-06-10 21:43',
    summary: '客户询问客服上班时间，希望知道什么时候回复。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-013',
    subject: '普通资料咨询',
    sender: 'buyer013@example.test',
    receivedAt: '2026-06-10 14:28',
    summary: '客户询问普通资料和处理流程，没有订单、退款或投诉诉求。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-014',
    subject: 'Sent the requested file',
    sender: 'buyer014@example.test',
    receivedAt: '2026-06-10 14:36',
    summary: '客户说明资料已经 sent，希望确认 received。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-015',
    subject: '查订单但没有信息',
    sender: 'buyer015@example.test',
    receivedAt: '2026-06-10 14:44',
    summary: '客户想查订单，缺少订单号，也未提供下单邮箱。',
    status: '待模拟验证',
  },
  {
    id: 'FMAIL-016',
    subject: '订单状态查询 SH-TEST-2020',
    sender: 'buyer016@example.test',
    receivedAt: '2026-06-10 14:52',
    summary: '客户提供订单号 SH-TEST-2020，询问订单状态。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-017',
    subject: '快递签收问题',
    sender: 'buyer017@example.test',
    receivedAt: '2026-06-10 15:03',
    summary: '客户询问快递是否已经签收。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-018',
    subject: 'tracking number update',
    sender: 'buyer018@example.test',
    receivedAt: '2026-06-10 15:11',
    summary: '客户询问 package tracking 信息。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-019',
    subject: '商品破损咨询',
    sender: 'buyer019@example.test',
    receivedAt: '2026-06-10 15:18',
    summary: '客户反馈商品破损，想知道售后流程，未提出退款。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-020',
    subject: 'Product issue, need help',
    sender: 'buyer020@example.test',
    receivedAt: '2026-06-10 15:24',
    summary: '客户描述 product issue after receiving，需要售后帮助。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-021',
    subject: '达人合作报价',
    sender: 'creator021@example.test',
    receivedAt: '2026-06-10 15:31',
    summary: '达人询问合作报价、寄样和合作流程。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-022',
    subject: 'Need help with my request',
    sender: 'buyer022@example.test',
    receivedAt: '2026-06-10 15:40',
    summary: '客户只说需要帮助，没有说明订单、物流、售后或合作诉求。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-023',
    subject: '多个问题一起咨询',
    sender: 'buyer023@example.test',
    receivedAt: '2026-06-10 15:49',
    summary: '客户同时询问订单、资料和处理流程，但没有明确优先诉求。',
    status: '待人工审核',
  },
  {
    id: 'FMAIL-024',
    subject: '我要取消订单并退款',
    sender: 'buyer024@example.test',
    receivedAt: '2026-06-10 16:02',
    summary: '客户要求取消订单并退款。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-025',
    subject: '要求补偿优惠券',
    sender: 'buyer025@example.test',
    receivedAt: '2026-06-10 16:12',
    summary: '客户要求补偿优惠券并希望马上处理。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-026',
    subject: '平台投诉处理',
    sender: 'buyer026@example.test',
    receivedAt: '2026-06-10 16:20',
    summary: '客户表示要平台申诉并投诉。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-027',
    subject: 'negative review warning',
    sender: 'buyer027@example.test',
    receivedAt: '2026-06-10 16:33',
    summary: '客户说如果不解决会留下 negative review。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-028',
    subject: '请修改订单数量',
    sender: 'buyer028@example.test',
    receivedAt: '2026-06-10 16:41',
    summary: '客户要求改数量并修改订单。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-029',
    subject: '什么时候到，今天能到吗',
    sender: 'buyer029@example.test',
    receivedAt: '2026-06-10 16:52',
    summary: '客户要求明确今天是否一定到货。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-030',
    subject: 'legal complaint',
    sender: 'buyer030@example.test',
    receivedAt: '2026-06-10 17:06',
    summary: '客户提到 lawyer 和 legal complaint。',
    status: '已拦截',
  },
  {
    id: 'FMAIL-031',
    subject: 'SEO backlinks and limited-time promotion',
    sender: 'promo031@example.test',
    receivedAt: '2026-06-10 17:20',
    summary: '广告推广、外链、群发营销，不涉及真实客户咨询。',
    status: '建议归入垃圾邮件',
  },
  {
    id: 'FMAIL-032',
    subject: '发票代开 加v',
    sender: 'spam032@example.test',
    receivedAt: '2026-06-10 17:26',
    summary: '疑似发票代开和加v推广内容，无订单或售后诉求。',
    status: '建议归入垃圾邮件',
  },
  {
    id: 'FMAIL-033',
    subject: '乱码群发测试垃圾',
    sender: 'junk033@example.test',
    receivedAt: '2026-06-10 17:31',
    summary: '乱码、群发、无效内容，判定为骚扰邮件样例。',
    status: '建议归入垃圾邮件',
  },
];
