export const orderSamples = [
  {
    orderId: 'SANDBOX-ORDER-1001',
    platform: 'ERP / 订单 CSV',
    orderStatus: '未发货',
    logisticsStatus: '待揽收',
    aftersaleStatus: '无售后',
    risk: 'medium',
    requiresManual: true,
    sourceStatus: 'CSV',
    sourceLabel: '订单 CSV 样例',
    reason: '订单未发货，需要客服或运营确认发货节奏，不自动承诺发货时间。',
  },
  {
    orderId: 'SANDBOX-ORDER-1002',
    platform: 'ERP / 订单 CSV',
    orderStatus: '已发货',
    logisticsStatus: '物流停滞',
    aftersaleStatus: '无售后',
    risk: 'high',
    requiresManual: true,
    sourceStatus: 'CSV',
    sourceLabel: '订单 CSV 样例',
    reason: '物流停滞可能引发投诉，进入高优先级异常。',
  },
  {
    orderId: 'SANDBOX-ORDER-1003',
    platform: 'ERP / 订单 CSV',
    orderStatus: '已支付',
    logisticsStatus: '未生成物流',
    aftersaleStatus: '客户催发货',
    risk: 'high',
    requiresManual: true,
    sourceStatus: 'CSV',
    sourceLabel: '订单 CSV 样例',
    reason: '客户催发货但不能自动承诺具体发货时间。',
  },
  {
    orderId: 'SANDBOX-ORDER-1004',
    platform: 'ERP / 订单 CSV',
    orderStatus: '已签收',
    logisticsStatus: '已签收',
    aftersaleStatus: '退款咨询',
    risk: 'high',
    requiresManual: true,
    sourceStatus: 'CSV',
    sourceLabel: '订单 CSV 样例',
    reason: '涉及退款咨询，必须人工处理，不能自动退款。',
  },
  {
    orderId: 'SANDBOX-ORDER-1005',
    platform: 'ERP / 订单 CSV',
    orderStatus: '已完成',
    logisticsStatus: '已签收',
    aftersaleStatus: '无售后',
    risk: 'low',
    requiresManual: false,
    sourceStatus: 'CSV',
    sourceLabel: '订单 CSV 样例',
    reason: '正常完成订单，只作为业务样例展示。',
  },
  {
    orderId: 'SANDBOX-ORDER-1006',
    platform: '订单 mock',
    orderStatus: '待确认',
    logisticsStatus: '未知',
    aftersaleStatus: '资料缺失',
    risk: 'medium',
    requiresManual: true,
    sourceStatus: 'mock',
    sourceLabel: '订单 mock 样例',
    reason: '缺少订单字段，用于演示待补齐数据，不代表真实订单。',
  },
];
